### ISSUE TITLE
ProgVal

### ISSUE THREAD

**Issue by Mikaela** [abgilpqt/abgilpqt.github.io#35]
@ProgVal removed themselves from the organization some days ago and probably isn't going to appear at the channel again either. The pages are full of them though, should it be said that they left or rewrite history or what?

**Comment by ProgVal** [comment]
(Could you update the topic so my two nicknames are not too easily linked by search engines?)

You don't have to rewrite history. If you just want to update pages it's fine.

**Comment by Mikaela** [comment]
> (Could you update the topic so my two nicknames are not too easily linked by search engines?)

done

> You don't have to rewrite history. If you just want to update pages it's fine.

Ok. Pages possibly require attention as they expect that you are present. And what should I do with the others who have left meaning @foxiepaws and KittenGNU?

I think people have changed so much that to follow the policy of having ops that people know they don't fill it, but I am still wishing we will be in speaking terms some day, but is what I feel and wish enough to override policies? It shouldn't be.
